<?php

namespace App\Console\Commands;

use App\Exceptions\InitializationException;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

use voku\helper\HtmlDomParser;

class MakeMarlinLabels extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'make:marlin-labels';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Convert a JSON file containing Marlin commands and labels into a platform-compatible enum.';

    const ENUMS_BASE_DIR = 'Enums';

    /**
     * Execute the console command.
     *
     * @return int
     */
    public function handle()
    {
        $generatedEnumPath  = self::ENUMS_BASE_DIR . '/' . env('MARLIN_GENERATED_ENUM_FILENAME', 'Marlin.php');

        $this->info('Fetching data from Marlin website...');

        $response = Http::get('https://marlinfw.org/meta/gcode/');

        if ($response->failed()) {
            throw new InitializationException('Failed to fetch data from Marlin website.');
        }

        $this->info('Parsing HTML content...');

        $dom = HtmlDomParser::str_get_html($response->body());

        $nodes = $dom->findMulti('.gcode h2');

        $commands = [];

        foreach ($nodes as $node) {
            $text = $node->text;

            list($command, $label) = explode(' - ', $text, 2);

            $keys = explode('-', $command);

            foreach ($keys as $key) {
                $subKeys = explode(', ', $key);

                foreach ($subKeys as $subKey) {
                    if (Str::contains($subKey, '.')) {
                        $subKey = Str::replaceMatches(
                            pattern: '/\..*/',
                            replace: '',
                            subject: $subKey
                        );
                    }

                    if (Str::match(pattern: '/[^a-zA-Z0-9]/', subject: $subKey)) {
                        $this->warn('Skipping invalid key: ' . $subKey);

                        continue;
                    }

                    $commands[trim($subKey)] = trim($label);
                }
            }
        }

        $this->info('Found ' . count($commands) . ' commands.');

        $this->info('Creating directory (if missing)...');

        Storage::disk('source')->makeDirectory( self::ENUMS_BASE_DIR );

        $this->info('Generating file "' . Storage::disk('source')->path($generatedEnumPath) . '"...');

        Storage::disk('source')->put(
            path: $generatedEnumPath,
            contents: 
                '<?php' . PHP_EOL .
                PHP_EOL .
                'declare(strict_types=1);' . PHP_EOL .
                PHP_EOL .
                'namespace App\Enums;' . PHP_EOL .
                PHP_EOL .
                'use BenSampo\Enum\Enum;' . PHP_EOL .
                PHP_EOL .
                '/*' . PHP_EOL .
                ' * This file has been auto-generated by running the "make:marlin-labels" Artisan' . PHP_EOL .
                ' * command. DO NOT edit it manually, if you\'ve got an updated list of commands,' . PHP_EOL .
                ' * simply run the generator again.' . PHP_EOL .
                ' */' . PHP_EOL .
                PHP_EOL .
                'final class Marlin extends Enum' . PHP_EOL .
                '{'
        );

        foreach ($commands as $command => $label) {
            Storage::disk('source')->append(
                path: $generatedEnumPath,
                data: "\t" . 'const ' . Str::replace(' ', '_', $command) . ' = \'' . $label . '\';'
            );
        }

        Storage::disk('source')->append(
            path: $generatedEnumPath,
            data:
                PHP_EOL .
                "\t" . 'public static function getLabel(string $gcodeLine) {' . PHP_EOL .
                "\t" . '    $command = preg_replace(\'/ ;.*/\', \'\', $gcodeLine);' . PHP_EOL .
                "\t" . '    $command = explode(\' \', $command, 2);' . PHP_EOL .
                PHP_EOL .
                "\t" . '    $output = \'?: Unknown\';' . PHP_EOL .
                PHP_EOL .
                "\t" . '    if (!$command || !$command[0]) {' . PHP_EOL .
                "\t" . '        return $output;' . PHP_EOL .
                "\t" . '    }' . PHP_EOL .
                PHP_EOL .
                "\t" . '    $params = trim($command[1] ?? \'\');' . PHP_EOL .
                PHP_EOL .
                "\t" . '    $output = "{$command[0]}: {$params}";' . PHP_EOL .
                PHP_EOL .
                "\t" . '    if ($params) { $output .= \' \'; }' . PHP_EOL .
                PHP_EOL .
                "\t" . '    $suffix = \'Unknown\';' . PHP_EOL .
                PHP_EOL .
                "\t" . '    if (self::hasKey($command[0])) {' . PHP_EOL .
                "\t" . '        $suffix = self::getValue($command[0]);' . PHP_EOL .
                "\t" . '    }' . PHP_EOL .
                PHP_EOL .
                "\t" . '    if ($params) {' . PHP_EOL .
                "\t" . '        $suffix = "({$suffix})";' . PHP_EOL .
                "\t" . '    }' . PHP_EOL .
                PHP_EOL .
                "\t" . '    return "{$output}{$suffix}";' . PHP_EOL .
                "\t" . '}' . PHP_EOL .
                PHP_EOL .
                '}' . PHP_EOL .
                PHP_EOL .
                '?>'
        );

        return Command::SUCCESS;
    }
}
