FROM alpine

# Install OS dependencies
RUN apk update && apk add --no-cache curl git unzip ca-certificates jq file bash

# Install OpenJDK 17 JDK (uncomment if needed)
# RUN apk add --no-cache openjdk17

# Install the Android SDK command line tools (uncomment if needed)
# RUN curl -o /tmp/android-commandlinetools-linux.zip https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip &&\
#     cd /tmp &&\
#     unzip /tmp/android-commandlinetools-linux.zip &&\
#     mkdir -p /tmp/android/sdk/cmdline-tools &&\
#     mv -v cmdline-tools /tmp/android/sdk/cmdline-tools/latest &&\
#     chmod +x /tmp/android/sdk/cmdline-tools/latest/bin/*

# Refresh SSL certificates
RUN update-ca-certificates

# Install Node.js 21.x
RUN apk add --no-cache nodejs npm

# Install Yarn
RUN npm install --global yarn

# Install PNPM
RUN npm install --global pnpm

# Copy the base code
ADD . /app

# Set the working directory
WORKDIR /app

# Install dependencies and build the frontend bundle if not in developer mode
RUN pnpm install --force --loglevel verbose

ENTRYPOINT [ "/app/entrypoint_dev.sh" ]
