FROM docker.io/library/php:8.4.12-bookworm

# Basic dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
        coreutils git curl redis-tools inotify-tools gnupg inetutils-ping \
        udev ffmpeg unzip supervisor psmisc jq uuid-runtime cron fswebcam \
        procps usbutils libzip-dev libmemcached-dev libyaml-dev libuv1-dev \
        libcurl4-openssl-dev libxml2-dev libzip-dev libevent-dev \
        libjpeg-dev libbsd-dev zlib1g-dev libssl-dev libdrm-dev libexif-dev \
        libboost-program-options-dev libglib2.0-dev libavcodec-dev libicu-dev \
        libgstreamer-plugins-base1.0-dev libjpeg62-turbo-dev libtiff5-dev \
        libpng-dev libavformat-dev libavutil-dev libjpeg62-turbo-dev libv4l-dev \
        python3 python3-pip &&\
    apt-get clean &&\
    rm -rf /var/lib/apt/lists/*

# Install the Docker CLI client
COPY --from=docker.io/library/docker:dind /usr/local/bin/docker           /usr/local/bin/
COPY --from=docker.io/library/docker:dind /usr/local/bin/docker-compose   /usr/local/bin/

# Install the Composer PHP package manager
COPY --from=docker.io/library/composer:latest /usr/bin/composer /usr/local/bin/composer

# PHP extensions: MongoDB + Redis + DIO (Direct I/O) + OpenSwooole + Memcached + YAML
RUN BUILD_TIME_DEPS='build-essential' &&\
    apt-get update && apt-get install -y --no-install-recommends $BUILD_TIME_DEPS &&\
    pecl install -f --onlyreqdeps --nobuild mongodb-1.21.0  &&\
    cd "$(pecl config-get temp_dir)/mongodb"                &&\
    phpize                                                  &&\
    ./configure                                             &&\
    make -j$(nproc --all) && make install                   &&\
    cd / && rm -rf "$(pecl config-get temp_dir)/mongodb"    &&\
    pecl install -f --onlyreqdeps --nobuild redis           &&\
    cd "$(pecl config-get temp_dir)/redis"                  &&\
    phpize                                                  &&\
    ./configure                                             &&\
    make -j$(nproc --all) && make install                   &&\
    cd / && rm -rf "$(pecl config-get temp_dir)/redis"      &&\
    pecl install -f --onlyreqdeps --nobuild dio             &&\
    cd "$(pecl config-get temp_dir)/dio"                    &&\
    phpize                                                  &&\
    ./configure                                             &&\
    make -j$(nproc --all) && make install                   &&\
    cd / && rm -rf "$(pecl config-get temp_dir)/dio"        &&\
    pecl install -f --onlyreqdeps --nobuild openswoole      &&\
    cd "$(pecl config-get temp_dir)/openswoole"             &&\
    phpize                                                  &&\
    ./configure                                             &&\
    make -j$(nproc --all) && make install                   &&\
    cd / && rm -rf "$(pecl config-get temp_dir)/openswoole" &&\
    pecl install -f --onlyreqdeps --nobuild memcached       &&\
    cd "$(pecl config-get temp_dir)/memcached"              &&\
    phpize                                                  &&\
    ./configure                                             &&\
    make -j$(nproc --all) && make install                   &&\
    cd / && rm -rf "$(pecl config-get temp_dir)/memcached"  &&\
    pecl install -f --onlyreqdeps --nobuild yaml            &&\
    cd "$(pecl config-get temp_dir)/yaml"                   &&\
    phpize                                                  &&\
    ./configure                                             &&\
    make -j$(nproc --all) && make install                   &&\
    cd / && rm -rf "$(pecl config-get temp_dir)/yaml"       &&\
    pecl install -f --onlyreqdeps --nobuild uv              &&\
    cd "$(pecl config-get temp_dir)/uv"                     &&\
    phpize                                                  &&\
    ./configure                                             &&\
    make -j$(nproc --all) && make install                   &&\
    cd / && rm -rf "$(pecl config-get temp_dir)/uv"         &&\
    apt-get purge -y $BUILD_TIME_DEPS &&\
    apt-get autoremove -y &&\
    apt-get clean &&\
    rm -rf /var/lib/apt/lists/*

# Enable PECL-based extensions: MongoDB + Redis + DIO (Direct I/O) + OpenSwoole + Memcached + YAML
RUN docker-php-ext-enable mongodb redis dio openswoole memcached yaml

# Install several officially supported PHP extensions: cURL, XML, ZIP, DOM, MySQLi, PDO MySQL, Sockets, PCNTL and Intl
RUN BUILD_TIME_DEPS='build-essential' &&\
    apt-get update && apt-get install -y --no-install-recommends $BUILD_TIME_DEPS &&\
    docker-php-ext-install -j$(( $(nproc --all) * 2 )) curl xml zip dom mysqli pdo_mysql sockets pcntl intl &&\
    apt-get purge -y $BUILD_TIME_DEPS &&\
    apt-get autoremove -y &&\
    apt-get clean &&\
    rm -rf /var/lib/apt/lists/*

# Build and install Camera Streamer and MJPG Streamer
#
# In the two blocks shown below, we will compile and install the RPi camera
# dependencies (libcamera) which are then bundled with the image. This is
# useful as most SBCs DO have a built-in hardware encoder/decoder that
# camera-streamer can take advantage of.
#
# Note that we're manually removing "input_raspicam" from MJPG streamer as it's
# broken on 64-bit builds of Raspberry Pi OS and it's terribly slow too, so
# we'll just build and use "input_libcamera" instead. As a side note, even
# though we're actually building "input_libcamera" into MJPG Streamer, we'll be
# using Camera Streamer instead whenever an RPi camera is found, as it's faster
# and more reliable.

# libcamera (RPi camera dependency - built and installed from source)
RUN if [ "$(dpkg --print-architecture)" = "arm64" ]; then \
        echo "Building and installing libcamera... " ;\
        BUILD_TIME_DEPS='build-essential cmake meson python3-jinja2 python3-ply python3-yaml xxd pkg-config debhelper dh-make' &&\
        apt-get update && apt-get install -y --no-install-recommends v4l-utils $BUILD_TIME_DEPS &&\
        git clone https://github.com/raspberrypi/libcamera.git --depth 1 -b v0.5.0+rpt20250429 /tmp/libcamera &&\
        cd /tmp/libcamera &&\
        meson build --buildtype=release -Dpipelines=rpi/vc4 -Dipas=rpi/vc4 -Dv4l2=true -Dgstreamer=enabled -Dtest=false -Dlc-compliance=disabled -Dcam=disabled -Dqcam=disabled -Ddocumentation=disabled -Dpycamera=disabled &&\
        ninja -C build install &&\
        apt-get purge -y $BUILD_TIME_DEPS &&\
        apt-get autoremove -y &&\
        apt-get clean &&\
        rm -rf /var/lib/apt/lists/* /tmp/libcamera &&\
        ldconfig ;\
    else \
        echo "Skipping libcamera build on non-arm64 architecture... " ;\
    fi

# camera-streamer
#
# 60c41f7 - ffmpeg: fix for latest FFMpeg library
# e08ba88 - webrtc: update libdatachannel to v0.23
# 9df363e - libdatachannel: force to update libdatachannel 
#
# Some of these changes break WebRTC support but we don't use WebRTC anyway,
# so it's not an issue.
RUN if [ "$(dpkg --print-architecture)" = "arm64" ]; then \
        echo "Building and installing camera-streamer... " ;\
        BUILD_TIME_DEPS='build-essential cmake meson python3-jinja2 python3-ply python3-yaml xxd pkg-config debhelper dh-make' &&\
        apt-get update && apt-get install -y --no-install-recommends v4l-utils $BUILD_TIME_DEPS &&\
        echo "Cloning camera-streamer repository... " &&\
        git clone https://github.com/wprint3d/camera-streamer.git --recursive --shallow-submodules /tmp/camera-streamer &&\
        cd /tmp/camera-streamer &&\
        echo "Continuing camera-streamer build... " &&\
        cd /tmp/camera-streamer &&\
        make -j$(( $(nproc --all) * 2 )) &&\
        echo "Installing camera-streamer... " ;\
        cd /tmp/camera-streamer &&\
        make install &&\
        cd .. &&\
        rm -rf /tmp/camera-streamer &&\
        apt-get purge -y $BUILD_TIME_DEPS &&\
        apt-get autoremove -y &&\
        apt-get clean &&\
        rm -rf /var/lib/apt/lists/* &&\
        rm -rf libcamera libcamera-apps camera-streamer/.git &&\
        ldconfig ;\
    else \
        echo "Skipping camera-streamer build on non-arm64 architecture... " ;\
    fi

# MJPG Streamer
RUN BUILD_TIME_DEPS='build-essential pkg-config cmake' &&\
    apt-get update && apt-get install -y --no-install-recommends $BUILD_TIME_DEPS &&\
    git clone https://github.com/ArduCAM/mjpg-streamer.git -b v1.0.2 --depth 1 &&\
    cd mjpg-streamer/mjpg-streamer-experimental &&\
    sed -i 's/add_subdirectory(plugins\/input_raspicam)//g' CMakeLists.txt &&\
    make -j$(( $(nproc --all) * 2 )) &&\
    make install &&\
    cd ../.. &&\
    rm -rf mjpg-streamer &&\
    apt-get purge -y $BUILD_TIME_DEPS &&\
    apt-get autoremove -y &&\
    apt-get clean &&\
    rm -rf /var/lib/apt/lists/*

# ustreamer
RUN BUILD_TIME_DEPS='build-essential pkg-config' &&\
    apt-get update && apt-get install -y --no-install-recommends $BUILD_TIME_DEPS &&\
    apt-get clean &&\
    rm -rf /var/lib/apt/lists/* &&\
    git clone --depth=1 https://github.com/pikvm/ustreamer &&\
    cd ustreamer &&\
    make -j$(( $(nproc --all) * 2 )) &&\
    make install &&\
    cd .. &&\
    rm -rf ustreamer &&\
    apt-get purge -y $BUILD_TIME_DEPS &&\
    apt-get autoremove -y &&\
    apt-get clean &&\
    rm -rf /var/lib/apt/lists/*

# Install gcodestat
RUN apt-get update && apt-get install -y --no-install-recommends build-essential &&\
    git clone https://github.com/wprint3d/gcodestat /root/gcodestat --depth 1 &&\
    cd /root/gcodestat &&\
    sed -i'' 's/CFLAGS := -Wall -Werror/CFLAGS := -Wall/' Makefile &&\
    make STATIC=0 NOCURL=1 -j$( nproc --all ) &&\
    mv gcodestat.exe gcodestat &&\
    find -not -name 'gcodestat' -delete &&\
    cd .. &&\
    apt-get purge -y build-essential &&\
    apt-get autoremove -y &&\
    apt-get clean &&\
    rm -rf /var/lib/apt/lists/*

# Copy PHP limits configuration
ADD ./internal/limits.ini /usr/local/etc/php/conf.d/limits.ini

# Copy PHP OPcache configuration template and setup script
COPY ./internal/php-opcache.ini.template /var/www/internal/php-opcache.ini.template
COPY ./internal/setup-php-opcache.sh /var/www/internal/setup-php-opcache.sh
COPY ./internal/php-opcache-preload.php /var/www/internal/php-opcache-preload.php

# Copy hardware detection and optimization scripts
COPY ./internal/detect-hardware.sh /var/www/internal/detect-hardware.sh
COPY ./internal/ramdisk-setup.sh /var/www/internal/ramdisk-setup.sh
COPY ./internal/app-cache-setup.sh /var/www/internal/app-cache-setup.sh

# Make scripts executable
RUN chmod +x /var/www/internal/setup-php-opcache.sh \
              /var/www/internal/detect-hardware.sh \
              /var/www/internal/ramdisk-setup.sh \
              /var/www/internal/app-cache-setup.sh

WORKDIR /var/www

RUN mkdir -p /usr/local/bin &&\
    echo 'Installing dependency: wait-for-it... ' &&\
    curl -s https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh -o /usr/local/bin/wait-for-it &&\
        chmod +x /usr/local/bin/wait-for-it

ENTRYPOINT [ "/var/www/internal/run.sh" ]
