services:
  proxy:
    image: nginx:stable
    restart: always
    logging:
      driver: local
      options:
        max-size: "16m"
        mode: non-blocking
    volumes:
      - ./proxy/nginxconfig.io:/etc/nginx/nginxconfig.io
      - ./proxy/internal:/etc/nginx/internal
      - ./proxy/conf.d:/etc/nginx/conf.d
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./proxy/ssl:/etc/nginx/ssl
      - ./public:/public
      - ./storage/app/recordings:/public/recordings
      - ./internal/startup:/internal/startup:ro
    ports:
      - ${EXTERNAL_WEB_HTTP_PORT:-80}:80
      - ${EXTERNAL_WEB_HTTPS_PORT:-443}:443
      - ${EXTERNAL_WEB_SOCKET_PORT:-6001}:6001
    depends_on:
      - web
      - ws-server
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    logging:
      driver: local
      options:
        max-size: "16m"
        mode: non-blocking
    privileged: true
    environment:
      - ROLE=server
      - DEVELOPER_MODE=true
    volumes:
      - .:/var/www
      - ./internal/limits.ini:/usr/local/etc/php/conf.d/limits.ini:ro
      - /dev/bus/usb:/dev/bus/usb
      - /dev:/dev
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc:/proc
    tmpfs:
      - /tmp
    depends_on:
      - redis
      - mongo
  web:
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    restart: always
    tty: true
    stdin_open: true
    volumes:
      - ./frontend:/app
    ports:
      - 8081:8081
    depends_on:
      - backend
      - redis
      - mongo
  scheduler:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    logging:
      driver: local
      options:
        max-size: "16m"
        mode: non-blocking
    privileged: true
    environment:
      - ROLE=scheduler
    volumes:
      - .:/var/www
      - ./internal/limits.ini:/usr/local/etc/php/conf.d/limits.ini:ro
      - /dev/bus/usb:/dev/bus/usb
      - /dev:/dev
    depends_on:
      - redis
      - mongo
  serial-scheduler:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    logging:
      driver: local
      options:
        max-size: "16m"
        mode: non-blocking
    privileged: true
    environment:
      - ROLE=serial-scheduler
    volumes:
      - .:/var/www
      - ./internal/limits.ini:/usr/local/etc/php/conf.d/limits.ini:ro
      - /dev/bus/usb:/dev/bus/usb
      - /dev:/dev
    depends_on:
      - redis
      - mongo
  mapper:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    logging:
      driver: local
      options:
        max-size: "16m"
        mode: non-blocking
    privileged: true
    environment:
      - ROLE=mapper
    volumes:
      - .:/var/www
      - ./internal/limits.ini:/usr/local/etc/php/conf.d/limits.ini:ro
      - /dev/bus/usb:/dev/bus/usb
      - /dev:/dev
      - /sys/class:/sys/class
      - /sys/devices:/sys/devices
      - /run/udev:/run/udev:ro
    depends_on:
      - redis
      - mongo
  queue:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    logging:
      driver: local
      options:
        max-size: "16m"
        mode: non-blocking
    privileged: true
    environment:
      - ROLE=queue
      - QUEUES=default:1,control:1,broadcasts:2,prints,previews,snapshots,recordings # <queue-name>:<min-number-of-workers, default=0>
      - SLEEP=5
    volumes:
      - .:/var/www
      - ./internal/limits.ini:/usr/local/etc/php/conf.d/limits.ini:ro
      - /dev/bus/usb:/dev/bus/usb
      - /dev:/dev
    depends_on:
      - redis
      - mongo
  ws-server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    logging:
      driver: local
      options:
        max-size: "16m"
        mode: non-blocking
    environment:
      - ROLE=ws-server
    volumes:
      - .:/var/www
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - redis
      - mongo
  streamer:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    logging:
      driver: local
      options:
        max-size: "16m"
        mode: non-blocking
    environment:
      - ROLE=streamer
      - PORT_SCAN_START=60000
      - PORT_SCAN_END=60016
    privileged: true
    volumes:
      - .:/var/www
      - ./internal/limits.ini:/usr/local/etc/php/conf.d/limits.ini:ro
      - /dev/bus/usb:/dev/bus/usb
      - /dev:/dev
      - /sys/class:/sys/class
      - /sys/devices:/sys/devices
      - /run/udev:/run/udev:ro
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - redis
      - mongo
      - proxy
      - mapper
  redis:
    image: redis:7.2.5
    restart: always
    logging:
      driver: local
      options:
        max-size: "16m"
        mode: non-blocking
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    command: redis-server --save "" --appendonly no
  mongo:
    image: mongo:4.4.6
    restart: always
    logging:
      driver: local
      options:
        max-size: "16m"
        mode: non-blocking
    command: mongod --quiet
    volumes:
      - mongo:/data/db
    ports:
      - 27017:27017
  memcached:
    image: memcached
    logging:
      driver: local
      options:
        max-size: "16m"
        mode: non-blocking
    restart: always
  documentation-generator:
    build:
      context: .
      dockerfile: Dockerfile.dev
    logging:
      driver: local
      options:
        max-size: "16m"
        mode: non-blocking
    environment:
      - ROLE=documentation-generator
    volumes:
      - .:/var/www
    ports:
      - 30000:30000
volumes:
  mongo: