services:
  proxy:
    image: wprint3d/wprint3d-proxy
    restart: always
    logging:
      driver: local
      options:
        max-size: "1m"
        mode: non-blocking
    volumes:
      - storage:/storage
      - proxy:/etc/nginx/internal
      - startup:/var/log/startup:ro
    ports:
      - ${EXTERNAL_WEB_HTTP_PORT:-80}:80
      - ${EXTERNAL_WEB_HTTPS_PORT:-443}:443
      - ${EXTERNAL_WEB_SOCKET_PORT:-6001}:6001
    depends_on:
      - web
      - backend
  backend:
    image: wprint3d/wprint3d
    restart: always
    logging:
      driver: local
      options:
        max-size: "1m"
        mode: non-blocking
    privileged: true
    environment:
      - ROLE=server
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /dev:/dev
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc:/proc
      - storage:/var/www/storage
      - proxy:/etc/nginx/internal
      - startup:/var/www/internal/startup
      - ./wprint3d-config:/var/www/.external-configs
    tmpfs:
      - /tmp
    depends_on:
      - redis
      - mongo
  web:
    image: wprint3d/wprint3d-frontend
    restart: always
    tty: true
    stdin_open: true
    depends_on:
      - backend
      - redis
      - mongo
  scheduler:
    image: wprint3d/wprint3d
    restart: always
    logging:
      driver: local
      options:
        max-size: "1m"
        mode: non-blocking
    privileged: true
    environment:
      - ROLE=scheduler
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /dev:/dev
      - storage:/var/www/storage
      - proxy:/etc/nginx/internal
      - startup:/var/www/internal/startup
      - ./wprint3d-config:/var/www/.external-configs
    depends_on:
      - redis
      - mongo
  mapper:
    image: wprint3d/wprint3d
    restart: always
    logging:
      driver: local
      options:
        max-size: "1m"
        mode: non-blocking
    privileged: true
    environment:
      - ROLE=mapper
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /dev:/dev
      - /sys/class:/sys/class
      - /sys/devices:/sys/devices
      - /run/udev:/run/udev:ro
      - storage:/var/www/storage
      - proxy:/etc/nginx/internal
      - startup:/var/www/internal/startup
      - ./wprint3d-config:/var/www/.external-configs
    depends_on:
      - redis
      - mongo
  concurrency-scheduler:
    image: wprint3d/wprint3d
    restart: always
    logging:
      driver: local
      options:
        max-size: "1m"
        mode: non-blocking
    privileged: true
    environment:
      - ROLE=concurrency-scheduler
      - QUEUES=default:1,broadcasts:2,prints,previews,snapshots,recordings # <queue-name>:<min-number-of-workers, default=0>
      - SLEEP=5
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /dev:/dev
      - storage:/var/www/storage
      - proxy:/etc/nginx/internal
      - startup:/var/www/internal/startup
      - ./wprint3d-config:/var/www/.external-configs
    depends_on:
      - redis
      - mongo
  streamer:
    image: wprint3d/wprint3d
    restart: always
    logging:
      driver: local
      options:
        max-size: "1m"
        mode: non-blocking
    environment:
      - ROLE=streamer
      - PORT_SCAN_START=60000
      - PORT_SCAN_END=60016
    privileged: true
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /dev:/dev
      - /sys/class:/sys/class
      - /sys/devices:/sys/devices
      - /run/udev:/run/udev:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - storage:/var/www/storage
      - proxy:/etc/nginx/internal
      - startup:/var/www/internal/startup
      - ./wprint3d-config:/var/www/.external-configs
    depends_on:
      - redis
      - mongo
      - proxy
      - mapper
  redis:
    image: redis:7.2.5
    restart: always
    logging:
      driver: local
      options:
        max-size: "1m"
        mode: non-blocking
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    command: redis-server --save "" --appendonly no
  mongo:
    image: mongo:4.4.6
    restart: always
    logging:
      driver: local
      options:
        max-size: "1m"
        mode: non-blocking
    command: mongod --quiet
    volumes:
      - mongo:/data/db
  memcached:
    image: memcached
    restart: always
    logging:
      driver: local
      options:
        max-size: "1m"
        mode: non-blocking
volumes:
  mongo:
  storage:
  proxy:
  startup: