version: "3.9"
services:
  proxy:
    image: nginx:stable
    restart: always
    volumes:
      - ./proxy/nginxconfig.io:/etc/nginx/nginxconfig.io
      - ./proxy/internal:/etc/nginx/internal
      - ./proxy/conf.d:/etc/nginx/conf.d
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./proxy/ssl:/etc/nginx/ssl
      - ./public:/public
      - ./storage/app/recordings:/public/recordings
      - ./internal/startup:/internal/startup:ro
    ports:
      - ${EXTERNAL_WEB_HTTP_PORT:-80}:80
      - ${EXTERNAL_WEB_HTTPS_PORT:-443}:443
      - ${EXTERNAL_WEB_SOCKET_PORT:-6001}:6001
    depends_on:
      - web
      - ws-server
  web:
    image: wprint3d/wprint3d
    restart: always
    privileged: true
    environment:
      - ROLE=server
    volumes:
      - .:/var/www
      - ./internal/limits.ini:/usr/local/etc/php/conf.d/limits.ini:ro
      - /dev/bus/usb:/dev/bus/usb
      - /dev:/dev
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - keydb
      - mongo
      - bundler
      # - mariadb
  scheduler:
    image: wprint3d/wprint3d
    restart: always
    privileged: true
    environment:
      - ROLE=scheduler
    volumes:
      - .:/var/www
      - ./internal/limits.ini:/usr/local/etc/php/conf.d/limits.ini:ro
      - /dev/bus/usb:/dev/bus/usb
      - /dev:/dev
    depends_on:
      - keydb
      - mongo
      # - mariadb
  # short-scheduler:
  #   image: wprint3d/wprint3d
  #   restart: always
  #   privileged: true
  #   environment:
  #     - ROLE=scheduler
  #     - KIND=short
  #   volumes:
  #     - .:/var/www
  #     - ./internal/limits.ini:/usr/local/etc/php/conf.d/limits.ini:ro
  #     - /dev/bus/usb:/dev/bus/usb
  #     - /dev:/dev
  #   depends_on:
  #     - keydb
  #     - mongo
  #     # - mariadb
  serial-scheduler:
    image: wprint3d/wprint3d
    restart: always
    privileged: true
    environment:
      - ROLE=serial-scheduler
    volumes:
      - .:/var/www
      - ./internal/limits.ini:/usr/local/etc/php/conf.d/limits.ini:ro
      - /dev/bus/usb:/dev/bus/usb
      - /dev:/dev
    depends_on:
      - keydb
      - mongo
      # - mariadb
  mapper:
    image: wprint3d/wprint3d
    restart: always
    privileged: true
    environment:
      - ROLE=mapper
    volumes:
      - .:/var/www
      - ./internal/limits.ini:/usr/local/etc/php/conf.d/limits.ini:ro
      - /dev/bus/usb:/dev/bus/usb
      - /dev:/dev
      - /sys/class/video4linux:/sys/class/video4linux
      - /sys/devices:/sys/devices
      - /run/udev:/run/udev:ro
    depends_on:
      - keydb
      - mongo
      # - mariadb
  queue:
    image: wprint3d/wprint3d
    restart: always
    privileged: true
    environment:
      - ROLE=queue
      - UPLOAD_LIMIT=1G
    volumes:
      - .:/var/www
      - ./internal/limits.ini:/usr/local/etc/php/conf.d/limits.ini:ro
      - /dev/bus/usb:/dev/bus/usb
      - /dev:/dev
    depends_on:
      - keydb
      - mongo
      # - mariadb
  prints-queue:
    image: wprint3d/wprint3d
    restart: always
    privileged: true
    environment:
      - ROLE=queue
      - QUEUE=prints
      - PARALLEL_JOBS_PER_THREAD=2
      - UPLOAD_LIMIT=1G
    volumes:
      - .:/var/www
      - ./internal/limits.ini:/usr/local/etc/php/conf.d/limits.ini:ro
      - /dev/bus/usb:/dev/bus/usb
      - /dev:/dev
    depends_on:
      - keydb
      - mongo
      # - mariadb
  control-queue:
    image: wprint3d/wprint3d
    restart: always
    privileged: true
    environment:
      - ROLE=queue
      - QUEUE=control
      - PARALLEL_JOBS_PER_THREAD=1
      - UPLOAD_LIMIT=1G
    volumes:
      - .:/var/www
      - ./internal/limits.ini:/usr/local/etc/php/conf.d/limits.ini:ro
      - /dev/bus/usb:/dev/bus/usb
      - /dev:/dev
    depends_on:
      - keydb
      - mongo
      # - mariadb
  previews-queue:
    image: wprint3d/wprint3d
    restart: always
    environment:
      - ROLE=queue
      - QUEUE=previews
      - UPLOAD_LIMIT=1G
    volumes:
      - .:/var/www
      - ./internal/limits.ini:/usr/local/etc/php/conf.d/limits.ini:ro
    depends_on:
      - keydb
      - mongo
      # - mariadb
  broadcasts-queue:
    image: wprint3d/wprint3d
    restart: always
    environment:
      - ROLE=queue
      - QUEUE=broadcasts
      - UPLOAD_LIMIT=1G
    volumes:
      - .:/var/www
      - ./internal/limits.ini:/usr/local/etc/php/conf.d/limits.ini:ro
      - /dev/bus/usb:/dev/bus/usb
      - /dev:/dev
    depends_on:
      - keydb
      - mongo
      # - mariadb
  snapshots-queue:
    image: wprint3d/wprint3d
    restart: always
    environment:
      - ROLE=queue
      - QUEUE=snapshots
      - SLEEP=0.25
    volumes:
      - .:/var/www
      - ./internal/limits.ini:/usr/local/etc/php/conf.d/limits.ini:ro
      - /dev/bus/usb:/dev/bus/usb
      - /dev:/dev
    depends_on:
      - keydb
      - mongo
      # - mariadb
  recordings-queue:
    image: wprint3d/wprint3d
    restart: always
    environment:
      - ROLE=queue
      - QUEUE=recordings
    volumes:
      - .:/var/www
      - ./internal/limits.ini:/usr/local/etc/php/conf.d/limits.ini:ro
      - /dev/bus/usb:/dev/bus/usb
      - /dev:/dev
    depends_on:
      - keydb
      - mongo
      # - mariadb
  ws-server:
    image: wprint3d/wprint3d
    restart: always
    environment:
      - ROLE=ws-server
    volumes:
      - .:/var/www
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - keydb
      - mongo
      # - mariadb
  bundler:
    image: wprint3d/wprint3d
    restart: always
    environment:
      - ROLE=bundler
    volumes:
      - .:/var/www
  streamer:
    image: wprint3d/wprint3d
    restart: always
    environment:
      - ROLE=streamer
      - PORT_SCAN_START=60000
      - PORT_SCAN_END=60016
    privileged: true
    volumes:
      - .:/var/www
      - ./internal/limits.ini:/usr/local/etc/php/conf.d/limits.ini:ro
      - /dev/bus/usb:/dev/bus/usb
      - /dev:/dev
      - /sys/class/video4linux:/sys/class/video4linux
      - /sys/devices:/sys/devices
      - /run/udev:/run/udev:ro
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - keydb
      - mongo
      - bundler
      - proxy
      # - mariadb
      - mapper
  keydb:
    image: eqalpha/keydb
    restart: always
    command: keydb-server --save "" --appendonly no # disable persistence
  mongo:
    image: mongo:4.4.6
    restart: always
    command: mongod --quiet
    volumes:
      - mongo:/data/db
  memcached:
    image: memcached
    restart: always
volumes:
  mongo: