ARG NGINX_IMAGE=docker.io/library/nginx:1.28-alpine

FROM ${NGINX_IMAGE}

COPY ./proxy/nginxconfig.io /etc/nginx/nginxconfig.io
COPY ./proxy/conf.d /etc/nginx/conf.d
COPY ./proxy/backend-upstream-http.conf /etc/nginx/backend-upstream.conf
COPY ./proxy/ssl /etc/nginx/ssl
COPY ./proxy/nginx.conf /etc/nginx/nginx.conf

RUN mkdir -p /internal/startup   &&\
    mkdir -p /public/recordings  &&\
    mkdir -p /etc/nginx/internal &&\
    ln -s /var/log/startup          /internal/startup   &&\
    ln -s /storage/app/recordings   /public/recordings  &&\
    touch /etc/nginx/internal/cameras.conf &&\
    touch /etc/nginx/internal/recordings.conf
